#-*- mode: ruby -*-
#vim: set ft=ruby :
# Домашняя работа №2

home_dir = ENV["HOME"]

MACHINES = {
  :"otus-lab2" => {
        :box_name => "geerlingguy/centos7",
        :ip_addr => '192.168.11.2',
        :disks => {
          :sata1 => {
            :dfile => home_dir + '\VirtualBox VMs/otus-lab-disk/lab2-sata1.vdi',
            :size => 256,
            :port => 2
          },
          :sata2=> {
            :dfile => home_dir + '\VirtualBox VMs/otus-lab-disk/lab2-sata2.vdi',
            :size => 256,
            :port => 3
          },
          :sata3 => {
            :dfile => home_dir + '\VirtualBox VMs/otus-lab-disk/lab2-sata3.vdi',
            :size => 256,
            :port => 4
          },
          :sata4 => {
            :dfile => home_dir + '\VirtualBox VMs/otus-lab-disk/lab2-sata4.vdi',
            :size => 256,
            :port => 5
          },
          :sata5 => {
            :dfile => home_dir + '\VirtualBox VMs/otus-lab-disk/lab2-sata5.vdi',
            :size => 256,
            :port => 6
          }
        }
  },
}

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|
    config.vm.define boxname do |box|
      box.vm.box = boxconfig[:box_name]
      box.vm.host_name = boxname.to_s
      box.vm.network "private_network", ip: boxconfig[:ip_addr]
      box.vm.synced_folder '.',"/home/vagrant/shared_folder/", type:"virtualbox" 
      box.vm.provider :virtualbox do |vb|
        vb.name = "otus-lab2"
        vb.customize ["modifyvm", :id, "--memory", "2048"]
        vb.customize ["modifyvm", :id, "--cpus", "4"]
        vb.customize ["storagectl", :id, "--name", "SATA", "--add", "sata"]
        boxconfig[:disks].each do |dname, dconf|
          unless File.exist?(dconf[:dfile])
            vb.customize ['createmedium', '--filename', dconf[:dfile], '--variant', 'Fixed', '--size', dconf[:size]]            
          end
          vb.customize ['storageattach', :id, '--storagectl', 'SATA', '--port', dconf[:port], '--device', 0, '--type', 'hdd', '--medium', dconf[:dfile]]
        end
      end
      #box.vm.provision "shell", path: "provision.sh"
      #box.vm.provision "shell", path: "tmux_provision.sh", privileged: false

    end
  end
end

