# -*- mode: ruby -*-
# vim: set ft=ruby :
# Лабараторная №1

distr_name = 'ncsot/centos7-otuslab'
lab_num = 'lab1'
vm_name = 'ncsot-' + lab_num
groups_name_path = '/ncsot-otuslab'
cpu_amt = 2
memory_size = 1024

Vagrant.configure("2") do |config|
  config.vbguest.auto_update = false
  config.vbguest.no_remote = true
  config.vm.box_check_update = false
  config.vm.box_version="0.0.2"
  config.vm.box = distr_name
  config.vm.host_name = vm_name
  config.vm.synced_folder '.',"/home/vagrant/shared_folder/", type:"virtualbox" 
  config.vm.provider :virtualbox do |vb|
    vb.name = vm_name
    vb.customize ["modifyvm", :id, "--memory", memory_size]
    vb.customize ["modifyvm", :id, "--cpus", cpu_amt]
    vb.customize ["modifyvm", :id, "--groups", groups_name_path]
  end
end
