# -*- mode: ruby -*-
# vim: set ft=ruby :
# Домашняя работа №1
MACHINES = {
  :"otus-lab1" => {
        :box_name => "geerlingguy/centos7",
        :ip_addr => '192.168.11.2'
  },
}

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|
    config.vm.define boxname do |box|
      box.vm.box = boxconfig[:box_name]
      box.vm.host_name = boxname.to_s
      box.vm.network "private_network", ip: boxconfig[:ip_addr]
      box.vm.synced_folder '.',"/home/vagrant/shared_folder/", type:"virtualbox" 
      box.vm.provider :virtualbox do |vb|
        vb.name = "otus-lab1"
        vb.customize ["modifyvm", :id, "--memory", "2048"]
        vb.customize ["modifyvm", :id, "--cpus", "4"]
        vb.customize ["modifyvm", :id, "--groups", "/otus-admin-course"]
        end
      box.vm.provision "shell", path: "../provision_scripts/provision.sh"
      box.vm.provision "shell", path: "../provision_scripts/tmux_provision.sh", privileged: false
      box.vm.provision "shell", path: "../provision_scripts/latest_kernel.sh"
    end
  end
end

