#-*- mode: ruby -*-
#vim: set ft=ruby :
# Лабараторная №3

distr_name = 'testlab3'
lab_num = 'lab3'
vm_name = 'ncsot-' + lab_num
home_dir = ENV["HOME"] + '/VirtualBox VMs'
groups_name_path = '/ncsot-otuslab'
disk_place = home_dir + groups_name_path
disk_name = 'replica-hdd'
disk_extension = "vmdk"
disk_size = 2000
disk_amt = 1
cpu_amt = 2
memory_size = 1024

Vagrant.configure("2") do |config|
  config.vbguest.auto_update = false
  config.vbguest.no_remote = true
  config.vm.box = distr_name
  #config.vm.box_version = '= 0.0.3'
  config.vm.box_check_update = false
  config.vm.host_name = vm_name
  config.vm.synced_folder '.',"/home/vagrant/shared_folder/", type:"virtualbox" 
  config.vm.provider :virtualbox do |vb|
    vb.name = vm_name
    vb.customize ["modifyvm", :id, "--memory", memory_size]
    vb.customize ["modifyvm", :id, "--cpus", cpu_amt]
    vb.customize ["modifyvm", :id, "--groups", groups_name_path]
    (1..disk_amt).each do |n|
      proceed_disk =  "%s/%s-%02d.%s" % [disk_place, disk_name, n, disk_extension]
      unless File.exist?(proceed_disk)
        vb.customize ['createmedium', '--filename', proceed_disk, '--format','vmdk','--variant', 'Standard', '--size', disk_size]
      end
    end
    (1..disk_amt).each do |n|
      proceed_disk =  "%s/%s-%02d.%s" % [disk_place, disk_name, n, disk_extension]
      vb.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', n+1, '--device', 0, '--type', 'hdd', '--medium', proceed_disk]
    end 
  end
end